name: test workflow

on:
  workflow_dispatch:
    inputs:
      user-name:
        type: string
        description: "Pplease give us username"
        required: true
        default: "Jude"
  push:
    branches:
      - main
  schedule:
    - cron: 2 * * * *

run-name: Run-${{ github.event_name }}

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: first step
        run: echo "hello ${{ github.event.inputs.user-name }}"

      - name: python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: listing
        run: |
          ls -ltr
          echo  "hello"

      - uses: actions/checkout@v4

      - name: listing after clone
        run: |
          ls -ltr
          echo  "hello" > output.txt

      - uses: actions/upload-artifact@v4
        with:
          name: my-artifact
          path: output.txt
          if-no-files-found: error # 'warn' or 'ignore' are also available, defaults to `warn`
