name: test workflow

on:
  workflow_dispatch:
  push:
    branches:
      - main
  schedule:
    - cron: 2 * * * *

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: first step
        run: echo "hell world"
