name: test workflow

on:
  workflow_dispatch:
    inputs:
      user-name:
        type: string
        description: "Pplease give us username"
        required: true
        default: "Jude"
  push:
    branches:
      - main
  schedule:
    - cron: 2 * * * *

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: first step
        run: echo "hello ${{ github.event.inputs.user-name }}"
