name: test workflow

on:
  workflow_dispatch:
    inputs:
      user-name:
        type: string
        description: "Pplease give us username"
        required: true
        default: "Jude"
  push:
    branches:
      - main
  schedule:
    - cron: 2 * * * *

run-name: Run-${{ github.event_name }}

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: first step
        run: echo "hello ${{ github.event.inputs.user-name }}"

      - name: python
        uses: actions/setup-python@v5
        #with:
        #python-version: '3.10'
